name: test_notify_github_trend

env:
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  QIITA_API_TOKEN: ${{ secrets.QIITA_API_TOKEN }}
  PROGRAM_LANGUAGES: ${{ secrets.PROGRAM_LANGUAGES }}
  ARTICLE_IDS: ${{ secrets.ARTICLE_IDS_TEST }}
  TRANSLATE_API_URL: ${{ secrets.TRANSLATE_API_URL }}
  NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN}}
  NOTION_DATABAE_ID: ${{ secrets.NOTION_DATABAE_ID}}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch #作業ブランチにchekout
        uses: actions/checkout@v2 #サードパーティの公開アクションを利用
        with:
          ref: ${{ github.ref }}
      - name: test notify github trend
        run: echo "test notify github trend" &&
          ls -al &&
          cat notify_ghtrend/resource/sample_qiita_request_body.json | jq '.private|=true' > notify_ghtrend/resource/qiita_request_body.json &&
          sed -e "s|__GH_ACCESS_TOKEN__|${GH_ACCESS_TOKEN}|g"
          -e "s|__QIITA_API_TOKEN__|${QIITA_API_TOKEN}|g"
          -e "s|__TRANSLATE_API_URL__|${TRANSLATE_API_URL}|g"
          -e "s|__PROGRAM_LANGUAGES__|${PROGRAM_LANGUAGES}|g"
          -e "s|__ARTICLE_IDS__|${ARTICLE_IDS}|g"
          -e "s|__NOTION_API_TOKEN__|${NOTION_API_TOKEN}|g"
          -e "s|__NOTION_DATABAE_ID__|${NOTION_DATABAE_ID}|g" .env.example > .env &&
          docker-compose up -d &&
          docker-compose exec -T poetry-demo poetry run python notify_ghtrend/main.py
